### PR TITLE
[rpm] remove test from rpm to make obs happy

### PR DESCRIPTION
**Pull request by alinelena**

### CODE REVIEW

**Comment by monich** [comment]
Hmm, what makes you think that obs is unhappy?

**Comment by alinelena** [comment]
Hi Slava,

I have built it on it and with your master with test in failed to run. 
https://build.merproject.org/package/live_build_log/nemo:devel:hw:common/harbour-books/sailfishos_1.1.9.28/armv8el
there is no issue with the test... as it happily runs in other parts. 
https://build.merproject.org/package/live_build_log/home:alin:extra/harbour-books/sailfishos_1.1.9.28/armv8el

I suspect is an issue of constraints on obs for common repo... but my past is experience is that a obs is good at testing not at running things.
Alin

**Comment by monich** [comment]
This was actually a problem with the test itself, it was crashing on the desktop just as nicely as in OBS. Commit faf85814 should fix it, please try again.

**Comment by alinelena** [comment]
Hi Slava,works indeed now!Thank you!


Alin



---
Dr Alin Marin Elenahttp://alin.elena.space



---- On Sun, 13 Sep 2015 10:25:43 +0000 Slava Monich &lt;notifications@github.com&gt; wrote ---- 

This was actually a problem with the test itself, it was crashing on the desktop just as nicely as in OBS. Commit faf8581 should fix it, please try again.

**Comment by monich** [comment]
OBS is happy now, closing this PR

**Pull request closed without merging**
