### PR TITLE
Create harbour-books-hu.ts

### PR DESCRIPTION
**Pull request by 1Zgp**
Hungarian translation for Books. Please add it to app.

### CODE REVIEW

**Comment by monich** [comment]
Could you please squash these changes into a single commit?

**Comment by 1Zgp** [comment]
Well, i am new on GitHub, i'll try it, sure.

**Comment by monich** [comment]
One way of fixing silly issues like missing quote or something (before this silliness is merged to master) is to `git add` the updated file and then `git commit --amend` followed by `git push -f`. That would update the last commit instead of creating a new one. If you have already created separate commits, you can `git merge --squash` them to a new branch which would turn them into a single commit. That's what I meant.

**Comment by monich** [comment]
I did the squashing myself then! (commit 0545fc631)

**Comment by 1Zgp** [comment]
Thanks, once again! I'm glad, you dit it.

**Pull request closed without merging**
