### PR TITLE
Update harbour-books-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Improved terminology to better fit OS

### CODE REVIEW

**Comment by monich** [comment]
Are you sure? I double-checked the terminology for Swedish translations, it says "top menu" => "Toppmeny", "pulley" => "rullgardinsmeny". Those are different things these days.

**Comment by eson57** [comment]
I think it actually is top menu in your Books app, and we had a discussion (which I can't find now) long time ago, where we decided that toppmeny is the better translation. It's more precise.
I actually can't remember one single app where pulley meny is not the same as top menu or bottom menu.
As a native Swedish speaking I am wondering, what "rullgardinsmeny"? Where is it? At the top or at the bottom?  ;-)

**Comment by monich** [comment]
This is top menu vs pulley menu:

Screenshot_20211114_002 Screenshot_20211114_001

BTW, russian translation for "pulley menu" also doesn't sound good to my ear (mostly because it's too long) but I couldn't come up with a translation better than the official one. A similar story here, I guess.

**Comment by monich** [comment]
But in the end it's your call - if you confirm that your translation is fine to a Swedish ear, I'll just merge it because I don't know Swedish at all and therefore don't really have any opinion on this subject.

**Comment by eson57** [comment]
> This is top menu vs pulley menu:
> 
> Screenshot_20211114_002 Screenshot_20211114_001
> 
> BTW, russian translation for "pulley menu" also doesn't sound good to my ear (mostly because it's too long) but I couldn't come up with a translation better than the official one. A similar story here, I guess.
Yes, I know the difference but they are both on top and the gesture is the same. I think we should stick to "toppmeny" because every swede knows exactly what I mean and it's more precise, I also use it in all my app translations, which is almost every Sailfish OS app.

**Comment by monich** [comment]
OK, thanks! Merging then.

**Pull request merged**
